using Catacombs.ElementSystem.Runtime;
using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;

namespace Argus.ItemSystem.Editor
{
    //This script is a clone of the ElementType SO containing only its variables, to be attached to SO prefabs generated by the Editor button in ElementTypeManager
    public class ElementData : UdonSharpBehaviour
    {
        [Header("Element")]
        public ElementTypes elementTypeId;
        public Color elementColor;


        [Header("Death Settings")]
        public bool canDespawn;
        public float killVelocity = Mathf.Infinity;
        public int despawnTime = 60;


        [Header("Base Element Settings")]
        public bool canCreatePrecipitate;
        public ElementPrecipitates elementPrecipitateType;
        public GameObject ElementPrecipitatePrefab;
        public float shrinkSpeed = 0.001f;
        public int elementPrecipitateAmount = 5;


        [Header("Precipitate Settings")]
        public bool scaleVelocity;
        public float targetVelocity;
        public float momentumScale = 1.01f;


        [Header("Spawner Settings")]
        public bool canCreateSpawners;
        public GameObject ElementSpawnerPrefab;
        public int elementSpawnerGrowthPeriod;
        public GameObject BaseElementPrefab;
        public int elementSpawnTime;
        public float seedGrowChance;
    }
}