using Catacombs.Base;
using Catacombs.ElementSystem.Runtime;
using UdonSharp;
using UnityEngine;

namespace Argus.ItemSystem.Editor
{
    //This script is a clone of the ElementType SO, to be attached to SO prefabs generated by the Editor button in ElementTypeManager
    public class ElementData : UdonSharpBehaviour
    {
        [Header("Element")]
        public ElementTypes elementTypeId;
        public Color elementColor;

        [Header("Death Settings")]
        public bool canDespawn;
        public float killVelocity = Mathf.Infinity;
        public int despawnTime = 60;

        [Header("Base Element Settings")]
        public bool canCreatePrecipitate;
        public ElementPrecipitates elementPrecipitateType;
        public GameObject ElementPrecipitatePrefab;
        public float shrinkSpeed = 0.001f;
        public int elementPrecipitateAmount = 5;

        [Header("Precipitate Settings")]
        public float minimumVelocity = 0;
        public float maximumVelocity = Mathf.Infinity;
        public float velocityMultiplier = 0.01f;

        [Header("Spawner Settings")]
        public bool canCreateSpawners;
        public float seedGrowChance;
        public int elementSpawnerGrowthPeriod;
        public int elementSpawnTime;
        public GameObject ElementSpawnerPrefab;
        public GameObject BaseElementPrefab;

        [Header("Potion Settings")]
        public bool elementIsPotion;
        public ElementPrimingTrigger potionPrimingTrigger;
        public int potionPrimingThreshold;
        public ElementUseTrigger potionUseTrigger;
        public PlayerEffect ingestedEffect;
        public int ingestedEffectStrength;
        public float ingestedEffectDuration;
        public GameObject GrownObjectPrefab;
        public float growTime;
    }
}