using Catacombs.ElementSystem.Runtime;
using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;

namespace Argus.ItemSystem.Editor
{
    //This script is a clone of the PotionType SO, to be attached to SO prefabs generated by the Editor button in ElementTypeManager
    public class PotionRecipeData : UdonSharpBehaviour
    {
        public Color potionColor;
        public ElementTypes potionElementType;
        public ElementTypes requiredLiquidType;
        public bool updateColor;
        public ElementTypes[] requiredElementTypes;
    }
}
